In [1]:
# general package
import tempfile
import os
import scipy
import numpy as np
import pandas as pd
import copy
import random

# single cell package
import scanpy as sc
import anndata as ad

# deep learning package
import torch
import torchvision.models as models
import torchvision.transforms as T
import torch.nn as nn
import torch.nn.functional as F
from torchvision.datasets import STL10
from torch.utils.data import DataLoader
from torch.multiprocessing import cpu_count
import torchvision.transforms as T

In [2]:
import DataLoader_tensor as dl

In [3]:
import numpy as np

# Set the parameters
n = 180  # Total number of data points
p = 5   # Number of features
M = 13   # Total number of groups

# Create the first array (n x p)
data_array = np.random.rand(n, p)  # Filling with random numbers for illustration

# Create the second array (n x 1)
# Ensure each group has at least two members
group_array = np.repeat(np.arange(1, M + 1), repeats=np.ceil(n / M))[:n]
np.random.shuffle(group_array)  # Shuffle to randomize group allocation
group_array = group_array.reshape(n, 1)

# print("Data Array (n x p):\n", data_array)
# print("Group Array (n x 1):\n", group_array)


In [4]:
data_array.shape, group_array.shape


((180, 5), (180, 1))

In [5]:
DLoader = dl.SClineage_DataLoader(data_array,group_array,batch_size=3)

In [6]:
len(DLoader)

180

In [7]:
x, y = DLoader.batch_generator()

In [8]:
x

{1: [(tensor([0.6068, 0.5960, 0.3608, 0.6502, 0.4842]),
   tensor([0.9162, 0.4830, 0.4081, 0.5147, 0.7856])),
  (tensor([0.4019, 0.9484, 0.5334, 0.6893, 0.1110]),
   tensor([0.3570, 0.1335, 0.0729, 0.5228, 0.6634])),
  (tensor([0.1334, 0.3979, 0.2869, 0.8386, 0.0108]),
   tensor([0.9812, 0.3263, 0.9304, 0.2178, 0.1559]))],
 2: [(tensor([0.4947, 0.3885, 0.4292, 0.3562, 0.2292]),
   tensor([0.9850, 0.1410, 0.5893, 0.3530, 0.7038])),
  (tensor([0.5016, 0.0464, 0.7915, 0.0945, 0.8046]),
   tensor([0.1832, 0.7893, 0.0633, 0.3102, 0.3934])),
  (tensor([0.0340, 0.1207, 0.6567, 0.3690, 0.8124]),
   tensor([0.5507, 0.6735, 0.0656, 0.2865, 0.9843]))],
 3: [(tensor([0.9459, 0.5025, 0.8337, 0.9264, 0.8438]),
   tensor([0.9446, 0.4732, 0.3453, 0.5697, 0.8498])),
  (tensor([0.2054, 0.1125, 0.5609, 0.1895, 0.4928]),
   tensor([8.4208e-01, 6.9230e-04, 1.2795e-01, 3.1866e-01, 2.2670e-01])),
  (tensor([0.9592, 0.8119, 0.9975, 0.0974, 0.0733]),
   tensor([0.2838, 0.1360, 0.7139, 0.7283, 0.1309]))],
 4: [

In [9]:
y

30

In [10]:
DLoader.lineage_indices

{9: [0, 6, 21, 33, 40, 41, 51, 87, 95, 103, 139, 147, 150, 151],
 8: [1, 2, 28, 54, 57, 69, 77, 84, 89, 105, 134, 137, 175, 178],
 1: [3, 9, 19, 27, 39, 72, 91, 96, 106, 143, 152, 168, 173, 179],
 5: [4, 10, 43, 46, 65, 83, 92, 101, 107, 119, 133, 149, 155, 156],
 4: [5, 7, 34, 37, 73, 79, 100, 111, 122, 127, 141, 154, 157, 163],
 11: [8, 24, 29, 31, 47, 56, 61, 67, 93, 99, 108, 114, 153, 177],
 10: [11, 14, 44, 50, 52, 53, 71, 90, 110, 115, 120, 144, 164, 176],
 7: [12, 23, 42, 58, 64, 75, 82, 86, 97, 102, 104, 125, 131, 165],
 2: [13, 17, 18, 22, 38, 81, 94, 109, 118, 135, 158, 160, 167, 170],
 13: [15, 25, 35, 49, 55, 78, 85, 116, 130, 140, 146, 171],
 6: [16, 30, 32, 48, 66, 98, 121, 129, 136, 145, 148, 161, 169, 172],
 12: [20, 26, 45, 60, 62, 80, 88, 123, 124, 132, 138, 142, 162, 166],
 3: [36, 59, 63, 68, 70, 74, 76, 112, 113, 117, 126, 128, 159, 174]}